apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: dunk
spec:
  selector:
    app: mysql
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: dunk
spec:
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - image: mysql:5.6
        imagePullPolicy: IfNotPresent #考慮到比較安全
        resources:
          requests:
            memory: "300Mi"
            cpu: "250m"
          limits:
            memory: "500Mi"
            cpu: "500m"
        livenessProbe:
          tcpSocket:
            port: 3306
          initialDelaySeconds: 10
          timeoutSeconds: 5
          failureThreshold: 5
          periodSeconds: 5
        readinessProbe:
          tcpSocket:
            port: 3306
          initialDelaySeconds: 10
          timeoutSeconds: 5
          failureThreshold: 5
          periodSeconds: 5
        name: mysql
        env:
          # Use secret in real usage
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: prod-db-secret
              key: username
              optional: false
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: prod-db-secret
              key: password
              optional: false
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: prod-db-secret
              key: database
              optional: false
        ports:
        - containerPort: 3306
          name: mysql
          protocol: TCP
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      restartPolicy: Always
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim
            
          