apiVersion: v1
kind: Service
metadata:
  name: my-service
  namespace: dunk
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 8010
      targetPort: 80
  type: LoadBalancer
  #loadBalancerIP: 35.209.131.236 should apply ip
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: dunk
  labels:
    app: nginx
spec:
  containers:
  - name: nginx
    image: nginx:latest
    resources:
      requests:
        memory: "50Mi"
        cpu: "150m"
      limits:
        memory: "100Mi"
        cpu: "200m"
    imagePullPolicy: IfNotPresent
    volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/
        - name: share-logs
          mountPath: /var/log/nginx
  - name: fluentd
    image: fluentd:latest
    imagePullPolicy: IfNotPresent
    resources:
      requests:
        memory: "50Mi"
        cpu: "150m"
      limits:
        memory: "100Mi"
        cpu: "200m"
    ports:
    volumeMounts:
        - name: fluentd-config
          mountPath: /fluentd/etc/
        - name: share-logs
          mountPath: /logs
  restartPolicy: Always
  volumes:
   - name: nginx-config
     configMap:
       name: nginx-configmap
       items:
         - key: nginx.conf
           path: nginx.conf
   - name: fluentd-config
     configMap:
       name: fluentd-configmap
       items:
         - key: fluentd.conf
           path: fluentd.conf
   - name: share-logs
     emptyDir: {}